### ISSUE TITLE
Daño variable de la maza

### ISSUE THREAD

**Issue by mihern07** [Proyectos1-FDI-UCM/c1920-Grupo03#11]
### Descripción

En ocasiones los enemigos mueren por un único ataque de maza en vez de por dos. Se esperaba que el daño de la maza fuera continuo.

### Pasos 

1. Selecciona la maza en la sala 1.
2. Derrota a los enemigos de la sala 2 con la maza.
3. Vuelve al menú y vuelve a repetir los pasos 1 y 2.
4. Los enemigos deberían de morir de forma variable dependiendo del momento.

**Comment by madelino22** [comment]
Esto era porque el arma de la lanza estaba también activada, entonces al escoger la maza o el arco también se iba con la lanza
