### ISSUE TITLE
“Bomber” no espera para estallar

### ISSUE THREAD

**Issue by jrubio05** [Proyectos1-FDI-UCM/c1920-Grupo03#19]
### Descripción
El enemigo “bomber” se detiene al explotar, mientras que en el plan elaborado por el equipo desarrollador consta que ha de detenerse antes de explotar.
### Pasos
1.	Ser atacado por un “bomber”. 
### Captura de pantalla o vídeo
![P2 8](https://user-images.githubusercontent.com/62879607/83329166-3bc15780-a288-11ea-8ad6-53e471131fd9.gif)

**Comment by madelino22** [comment]
La explosión de la bomba es justo cuando desaparece, no cuando aparece el circulo blanco, por lo que está bien como está.

**Comment by AlexSopena** [comment]
Así es, el círculo blanco es simplemente un indicador del área que va a afectar.
