### ISSUE TITLE
El ataque de los Arqueros no hace daño

### ISSUE THREAD

**Issue by samuebla** [Proyectos1-FDI-UCM/c1920-Grupo03#2]
Ataque arqueros
Descripción
Las flechas de los arqueros no hacen daño al jugador sin importar donde mires
Pasos
1.	Entra en el nivel 1
2.	Ve a una sala con arqueros
Captura de pantalla o vídeo
[https://youtu.be/oPQKIHWNGYE](url)

**Comment by mihern07** [comment]
Como pequeño añadido colisionar con los arqueros tampoco daña al jugador, no se si esto es intencionado.

**Comment by madelino22** [comment]
Los arqueros no deben hacer daño al colisionar, y no hacían daño porque faltaba añadir el takedamage del gameManager
