### ISSUE TITLE
Áreas con retraso

### ISSUE THREAD

**Issue by jrubio05** [Proyectos1-FDI-UCM/c1920-Grupo03#20]
### Descripción
Las áreas de daño utilizadas por los “bomber” y el jefe final infligen daño al desaparecer. Se esperaba que lo hiciesen al aparecer.
### Pasos
1.	Acercarse a un enemigo que genere áreas de daño.
2.	Ser alcanzado por el área y permanecer en ella hasta que desaparezca.
### Captura de pantalla o vídeo
![P2 9](https://user-images.githubusercontent.com/62879607/83329199-690e0580-a288-11ea-8a2a-42cca04f2809.gif)

**Comment by madelino22** [comment]
Ese área es para avisar al jugador de que va a explotar y pueda esquivarlo. No hay ningún fallo aquí.
