### ISSUE TITLE
Posible error del personaje

### ISSUE THREAD

**Issue by druiz07** [Proyectos1-FDI-UCM/c1920-Grupo03#22]
El moimiento a veces se fusiona con la rotacion y no puedes hacer una cosa u otra , te mueves a la vez que rotas y eso no deberia de ser asi 
Pasos
1.	Empezar en la sala y moverte a cualquier lado 
2.	De primeras sin usar el raton ya se observara que el jugador esta rotando sin necesidad del axis del ratos , y solo con el uso de flechas /wasd

**Comment by jrubio05** [comment]
XDD
Supongo que es comportamiento esperado; así lo vi yo. El personaje siempre mira hacia el cursor.

**Comment by jrubio05** [comment]
Este informe de error parece haberse marcado como cerrado para dar paso a una nueva versión, que ha sido bautizada como #23, actualmente abierta. @druiz07, deberías haber editado y reabierto este informe, no crear duplicados.
