### ISSUE TITLE
Posible error del personaje

### ISSUE THREAD

**Issue by druiz07** [Proyectos1-FDI-UCM/c1920-Grupo03#23]
El movimiento a veces se fusiona con la rotacion y no puedes hacer una cosa u otra , te mueves a la vez que rotas y eso no deberia de ser asi 
Pasos
1.	Empezar en la sala y moverte a cualquier lado 
2.	De primeras sin usar el raton ya se observara que el jugador esta rotando sin necesidad del axis del ratos , y solo con el uso de flechas /wasd

**Comment by jrubio05** [comment]
Este informe de error parece ser una copia de #22, cerrado por algún motivo.

**Comment by AlexSopena** [comment]
Cerrado porque este comportamiento sí que es esperado, el jugador siempre mira al ratón.
