### ISSUE TITLE
Trampas desactivadas por anillo

### ISSUE THREAD

**Issue by jrubio05** [Proyectos1-FDI-UCM/c1920-Grupo03#25]
### Descripción
Las trampas de la sala del anillo se desactivan al recoger el objeto. Nota: dudo de la intencionalidad de este comportamiento.
### Pasos
1.	Acceder a la sala del anillo.
2.	Coger el anillo.
3.	Colocarse sobre una trampa.
### Captura de pantalla o vídeo
![L 2](https://user-images.githubusercontent.com/62879607/83329470-0289e700-a28a-11ea-82ba-e3d220c62f6b.gif)

**Comment by Jonandra** [comment]
Sí, es intencionado el comportamiento, aunque si que es verdad que el comportamiento de la trampa establecido en el GDD no sea lo eficaz o no proporcione la dificultad pensada.
