### ISSUE TITLE
“Bomber” interrumpido

### ISSUE THREAD

**Issue by jrubio05** [Proyectos1-FDI-UCM/c1920-Grupo03#27]
### Descripción
El enemigo “bomber” puede ser destruido mientras está explotando.
### Pasos
1.	Encontrar un “bomber”.
2.	Dejar que se acerque y estalle.
3.	Matarlo antes de que desaparezca.
### Captura de pantalla o vídeo
![L 6](https://user-images.githubusercontent.com/62879607/83329961-9361c200-a28c-11ea-816f-3211f0896a05.gif)

**Comment by madelino22** [comment]
Eso es lo que debería pasar.
