### ISSUE TITLE
Muros atrapaflechas

### ISSUE THREAD

**Issue by jrubio05** [Proyectos1-FDI-UCM/c1920-Grupo03#28]
### Descripción
Probablemente vinculado con #26. En la primera sala con enemigos, al disparar al muro lateral derecho, algunas flechas se destruyen (comportamiento esperado), pero otras se quedan pegadas, lo traspasan o hasta rebotan (inesperado). Las flechas parecen solo poder traspasar el muro al despejar la sala (las que rebotan o se pegan lo hacen tanto antes de completarla como después).
### Pasos
1.	Elegir el arma “arco”.
2.	Llegar a la sala “2”.
3.	Completar la sala.
4.	Disparar flechas a distintas alturas del muro derecho.
### Captura de pantalla o vídeo
![L 7](https://user-images.githubusercontent.com/62879607/83330029-fe12fd80-a28c-11ea-813c-e10873dc8d36.gif)

**Comment by Jonandra** [comment]
Solucionado, gracias
