### ISSUE TITLE
Flechas entre cámaras

### ISSUE THREAD

**Issue by jrubio05** [Proyectos1-FDI-UCM/c1920-Grupo03#29]
### Descripción
Derivado en parte de #28. Una flecha puede atravesar diversas habitaciones si se cuela por las entradas o si atraviesa un muro. Esto también implica que se puede vencer a enemigos de una sala cercana sin haber entrado aún en ella.
### Pasos
1.	Elegir el arma “arco”.
2.	Despejar las salas a testar si se desea (al menos se ha de despejar la sala desde la que se disparará).
3.	Lanzar una flecha desde una sala a otra por el hueco de la puerta.
4.	Correr siguiendo a la flecha.
5.	Pasar a la habitación adyacente a tiempo para ver el proyectil aún en vuelo.
### Captura de pantalla o vídeo
![L 8](https://user-images.githubusercontent.com/62879607/83330155-a1641280-a28d-11ea-8790-6a6c63673b3b.gif)

**Comment by Jonandra** [comment]
Solucionado
