### ISSUE TITLE
El boss del nivel1 se autodestruye

### ISSUE THREAD

**Issue by samuebla** [Proyectos1-FDI-UCM/c1920-Grupo03#3]
AutoDestrucción Boss Nivel1
Descripción
Si pegas al enemigo final una sola vez y no te mueves el enemigo se autodestruye y no te hace daño.
Pasos
1.	Ve al nivel 1
2.	Dirígete a la sala del boss final
3.	Pégale una vez y no te muevas
Captura de pantalla o vídeo
[https://youtu.be/cEwdNRIaHag](url)

**Comment by madelino22** [comment]
No se que hemos hecho pero ya no se destruye XD

**Comment by jrubio05** [comment]
Quizá tenga que ver con el error "Daño variable de la maza".

**Comment by madelino22** [comment]
No creo que fuera por ese error ya que tenía que ver con una cosa de la lanza, pero ya están arreglados.
