### ISSUE TITLE
Palabra "menu"

### ISSUE THREAD

**Issue by jrubio05** [Proyectos1-FDI-UCM/c1920-Grupo03#36]
### Descripción
En los menús de pausa, muerte y victoria la palabra "menu" aparece en lugar de "menú".
### Pasos
1.	Llegar a uno de los menús citados.
### Captura de pantalla o vídeo
![L e1 1](https://user-images.githubusercontent.com/62879607/83330681-213fac00-a291-11ea-86aa-f54728638e20.png)
![L e1 2](https://user-images.githubusercontent.com/62879607/83330683-21d84280-a291-11ea-9b08-3b55f9349cee.png)
![L e1 3](https://user-images.githubusercontent.com/62879607/83330680-1f75e880-a291-11ea-9c37-91c021c893b4.png)

**Comment by madelino22** [comment]
Nos parecía y nos sigue pareciendo más estético de esta manera, pero gracias.
